function f = fbenney2dTransformed(domain, z, params)
    r2 = sqrt(2);

    z34 = z.^(3/4);
    P = 8 * cot(params.theta) * z - ...
        1/params.C * (...
        (domain.diff(z, [2; 0]) + domain.diff(z, [0; 2])) - ...
        3/4 * (domain.diff(z, [1; 0]).^2 + domain.diff(z, [0; 1]).^2)./z ...
        );

    F1 = 4*r2/3 * z34 - ...
        1/3 * (domain.diff(P, [1; 0]) - 3/4 * domain.diff(z, [1; 0])./z .* P) + ...
        16*r2/15 * params.Re * z34 .* domain.diff(z, [1; 0]);

    F2 = - 1/3 * (domain.diff(P, [0; 1]) - 3/4 * domain.diff(z, [0; 1])./z .* P);

    f = - 2*r2 * z34 .* (domain.diff(F1, [1; 0]) + domain.diff(F2, [0; 1]));
end
