function dYdt = fwibl1(domain, Y, params)

    epsilon = 1;

    Y = domain.reshapeToDomain(Y);

    h = Y(1:end/3, :, :);
    F1 = Y(end/3+1:2*end/3, :, :);
    F2 = Y(2*end/3+1:end, :, :);

    dhdx = domain.diff(h, [1; 0]);
    d3hdx3 = domain.diff(h, [3; 0]);
    dhdz = domain.diff(h, [0; 1]);
    d3hdz3 = domain.diff(h, [0; 3]);
    d3hdx2z = domain.diff(h, [2; 1]);
    d3hdxz2 = domain.diff(h, [1; 2]);

    dF1dx = domain.diff(F1, [1; 0]);
    dF1dz = domain.diff(F1, [0; 1]);
    
    dF2dx = domain.diff(F2, [1; 0]);
    dF2dz = domain.diff(F2, [0; 1]);
    
    dhdt = - dF1dx - dF2dz;

    dF1dt = ...
        m(-17*m(F1,dF1dx) ...
		- 8*m(F1,dF2dz) ...
		- 9*m(F2,dF1dz),(7*h),[1,-1]) ...
		+ m(9*m(F1,dhdx,[2,1])/7 ...
		+ 9*m(m(F1,F2),dhdz)/7,h,[1,-2]) ...
		- 5*cot(params.theta)*m(h,dhdx)/(3*params.Re) ...
		+ 5*h/(3*params.Re*epsilon) ...
		- 5*m(F1,h,[1,-2])/(2*params.Re*epsilon) ...
		+ 5*m(h,d3hdx3)/(6*params.C*params.Re*epsilon) ...
		+ 5*m(h,d3hdxz2)/(6*params.C*params.Re*epsilon);

    dF2dt = ...
		m(-9*m(F1,dF2dx) ...
		- 8*m(F2,dF1dx) ...
		- 17*m(F2,dF2dz),(7*h),[1,-1]) ...
		+ m(9*m(m(F1,F2),dhdx)/(7) ...
		+ 9*m(F2,dhdz,[2,1])/(7),h,[1,-2]) ...
		- 5*cot(params.theta)*m(h,dhdz)/(3*params.Re) ...
		- 5*m(F2,h,[1,-2])/(2*params.Re*epsilon) ...
		+ 5*m(h,d3hdz3)/(6*params.C*params.Re*epsilon) ...
		+ 5*m(h,d3hdx2z)/(6*params.C*params.Re*epsilon);

    dYdt = cat(1, dhdt, dF1dt, dF2dt);

    dYdt = domain.reshapeToVector(dYdt);

    function c = m(a,b,pow)
        if nargin<3, pow = [1,1]; end

        c = domain.multiply(a,b,pow);
    end
end
