function [A] = linearisedWIBL2STFFourier(domain, hbar, F1bar, F2bar, params, alpha)
    beta = 0;
    epsilon = 1;

    N = prod(domain.shape)*3;

    hbarz = domain.ifft(domain.diff(domain.fft(hbar), 1));
    hbarz2 = domain.ifft(domain.diff(domain.fft(hbar), 2));
    hbarz3 = domain.ifft(domain.diff(domain.fft(hbar), 3));
    F1barz = domain.ifft(domain.diff(domain.fft(F1bar), 1));
    F2barz = domain.ifft(domain.diff(domain.fft(F2bar), 1));

    A = zeros(N, N);

    for n = 1:N
        y = zeros(N,1);
        y(n) = 1;
        
        fhhat = y(1:end/3);
        fF1hat = y(1+end/3:2/3*end);
        fF2hat = y(1+2*end/3:end);

        hhat = domain.ifft(fhhat);
        hhatz = domain.ifft(domain.diff(fhhat, 1));
        hhatz2 = domain.ifft(domain.diff(fhhat, 2));
        hhatz3 = domain.ifft(domain.diff(fhhat, 3));
        hhatz4 = domain.ifft(domain.diff(fhhat, 4));

        F1hat = domain.ifft(fF1hat);
        F1hatz = domain.ifft(domain.diff(fF1hat, 1));
        F1hatz2 = domain.ifft(domain.diff(fF1hat, 2));

        F2hat = domain.ifft(fF2hat);
        F2hatz = domain.ifft(domain.diff(fF2hat, 1));
        F2hatz2 = domain.ifft(domain.diff(fF2hat, 2));

        A1 = -1i.*alpha.*F1hat ...
            - F2hatz;

        A2 = -17.*1i.*alpha.*F1bar.*F1hat./(7.*hbar) ...
            + 9.*1i.*alpha.*hhat.*F1bar.^2./(7.*hbar.^2) ...
            - 8.*epsilon.*F1bar.*F2hatz./(7.*hbar) ...
            - 8.*epsilon.*F1hat.*F2barz./(7.*hbar) ...
            - 9.*epsilon.*F2bar.*F1hatz./(7.*hbar) ...
            - 9.*epsilon.*F2hat.*F1barz./(7.*hbar) ...
            + 8.*epsilon.*hhat.*F1bar.*F2barz./(7.*hbar.^2) ...
            + 9.*epsilon.*hhat.*F2bar.*F1barz./(7.*hbar.^2) ...
            + 9.*epsilon.*F1bar.*F2bar.*hhatz./(7.*hbar.^2) ...
            + 9.*epsilon.*F1bar.*F2hat.*hbarz./(7.*hbar.^2) ...
            + 9.*epsilon.*F1hat.*F2bar.*hbarz./(7.*hbar.^2) ...
            - 18.*epsilon.*hhat.*F1bar.*F2bar.*hbarz./(7.*hbar.^3) ...
            - 9.*alpha.^2.*epsilon.*F1hat./(2.*params.Re) ...
            + 6.*alpha.^2.*epsilon.*hhat.*F1bar./(params.Re.*hbar) ...
            - 5.*1i.*alpha.*hbar.*hhat.*cot(params.theta)./(3.*params.Re) ...
            + epsilon.*F1hatz2./params.Re ...
            - 23.*epsilon.*F1bar.*hhatz2./(16.*params.Re.*hbar) ...
            - 23.*epsilon.*F1hat.*hbarz2./(16.*params.Re.*hbar) ...
            - epsilon.*hbarz.*F1hatz./(params.Re.*hbar) ...
            - epsilon.*hhatz.*F1barz./(params.Re.*hbar) ...
            + 23.*epsilon.*hhat.*F1bar.*hbarz2./(16.*params.Re.*hbar.^2) ...
            + epsilon.*hhat.*hbarz.*F1barz./(params.Re.*hbar.^2) ...
            + 3.*epsilon.*F1bar.*hbarz.*hhatz./(2.*params.Re.*hbar.^2) ...
            + 3.*epsilon.*F1hat.*hbarz.^2./(4.*params.Re.*hbar.^2) ...
            - 3.*epsilon.*hhat.*F1bar.*hbarz.^2./(2.*params.Re.*hbar.^3) ...
            + 5.*hhat./(3.*params.Re.*epsilon) ...
            - 5.*F1hat./(2.*params.Re.*epsilon.*hbar.^2) ...
            + 5.*hhat.*F1bar./(params.Re.*epsilon.*hbar.^3) ...
            - 5.*1i.*alpha.^3.*hbar.*hhat./(6.*params.C.*params.Re.*epsilon) ...
            + 5.*1i.*alpha.*hbar.*hhatz2./(6.*params.C.*params.Re.*epsilon);

        A3 = -9.*1i.*alpha.*epsilon.*F1bar.*F2hat./(7.*hbar) ...
            - 8.*1i.*alpha.*epsilon.*F1hat.*F2bar./(7.*hbar) ...
            + 9.*1i.*alpha.*epsilon.*hhat.*F1bar.*F2bar./(7.*hbar.^2) ...
            + 7.*1i.*alpha.*epsilon.*F1hatz./(2.*params.Re) ...
            - 43.*1i.*alpha.*epsilon.*hhat.*F1barz./(16.*params.Re.*hbar) ...
            - 73.*1i.*alpha.*epsilon.*F1bar.*hhatz./(16.*params.Re.*hbar) ...
            - 13.*1i.*alpha.*epsilon.*F1hat.*hbarz./(16.*params.Re.*hbar) ...
            + 13.*1i.*alpha.*epsilon.*hhat.*F1bar.*hbarz./(4.*params.Re.*hbar.^2) ...
            - 5.*hbar.*cot(params.theta).*hhatz./(3.*params.Re) ...
            - 5.*hhat.*cot(params.theta).*hbarz./(3.*params.Re) ...
            - 5.*F2hat./(2.*params.Re.*hbar.^2) ...
            + 5.*hhat.*F2bar./(params.Re.*hbar.^3) ...
            - 5.*alpha.^2.*hbar.*hhatz./(6.*params.C.*params.Re.*epsilon) ...
            + 5.*hbar.*hhatz3./(6.*params.C.*params.Re.*epsilon) ...
            + 5.*hhat.*hbarz3./(6.*params.C.*params.Re.*epsilon);

        A(1:N,n) = [domain.fft(A1); ...
            domain.fft(A2); ...
            domain.fft(A3)];
    end

end
