function E = norm_H2(x,y,method)
    deg = [1,0;0,1;2,0;0,2]';
    y = reshape(y,numel(y),1);
    dy = method(x,y,deg);
    
    % E = int( f^2 + f_x^2 + f_y^2 + f_xx^2 + f_yy^2 ) ^ (1/2)
    E = sum((y - 1).^2 + ...
        cell2mat(...
        cellfun(@(dy) reshape(dy,numel(dy),1)',dy,'UniformOutput',false)...
        )'.^2,'all') * ...
        x{1}(1) * x{2}(1);
end
