function timeStepper = setupTimeStepper(method, model, domain, params, AbsTol, debug)
     odeopt = odeset( ...
            ...'Vectorized', 'on', ...
            ...'BDF','on', ...
            'AbsTol', AbsTol ...
            ...'MaxStep', 5e-6 ...
            ...'InitialStep', 1e-3 ...
            );
        if debug
            odeopt = odeset(odeopt, ...
                'OutputFcn', 'odeprint', ...
                'OutputSel', 1, ...
                'Stats', 'on');
        end
        
        if method == "finite-difference"
            if model == "benney"
                odeopt = odeset(odeopt, ...
                    'Jacobian', @(t, y) jbenney2d(domain, y, params) ...
                    );
            end
        end
        
        if method == "finite-difference"
            timeStepper = @(odefun, t, y0) ode15s(odefun, t, y0, odeopt);
        elseif method == "pseudo-spectral"
            timeStepper = @(odefun, t, y0) ode15s(odefun, t, y0, odeopt);
        end
    
    
end